### ISSUE TITLE
Add dependencies to cog.json files

### ISSUE THREAD

**Issue by DeathlyKnife** [calebj/calebj-cogs#20]
i get this message when i try to install the punish cog.
Copying punish...
[21/03/2017 12:31] ERROR owner load 75: You must run `pip3 install tabulate`.
Traceback (most recent call last):
  File "D:\Ryy-DiscordBot\cogs\punish.py", line 11, in <module>
    from tabulate import tabulate
ImportError: No module named 'tabulate'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Ryy-DiscordBot\cogs\owner.py", line 65, in load
    self._load_cog(module)
  File "D:\Ryy-DiscordBot\cogs\owner.py", line 797, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\impor
lib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "D:\Ryy-DiscordBot\cogs\punish.py", line 13, in <module>
    raise RuntimeError("You must run `pip3 install tabulate`.") from e
RuntimeError: You must run `pip3 install tabulate`.
Traceback (most recent call last):
  File "D:\Ryy-DiscordBot\cogs\punish.py", line 11, in <module>
    from tabulate import tabulate
ImportError: No module named 'tabulate'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Ryy-DiscordBot\cogs\owner.py", line 65, in load
    self._load_cog(module)
  File "D:\Ryy-DiscordBot\cogs\owner.py", line 797, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\impor
lib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "D:\Ryy-DiscordBot\cogs\punish.py", line 13, in <module>
    raise RuntimeError("You must run `pip3 install tabulate`.") from e
RuntimeError: You must run `pip3 install tabulate`.

**Comment by calebj** [comment]
As it says, you should probably run `pip3 install tabulate`. With the new launcher, the command is:
`pip3 install --upgrade --target libs tabulate`.

I'm leaving this open until I add tags and dependencies to my cog.json files.

**Comment by calebj** [comment]
Fixed in dda9672b6f6f4c698b3a8604e3b8c342fcf9bd79
