### ISSUE TITLE
Punish not working.

### ISSUE THREAD

**Issue by iiTranquility** [calebj/calebj-cogs#27]
`[13/04/2017 03:57] ERROR red on_command_error 375: Exception in command 'punish'
Traceback (most recent call last):
  File "lib\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\iiCarelessness\Desktop\All My Shit\Programs\Red-DiscordBot\cogs\punish.py", line 106, in punish
    await self._punish_cmd_common(ctx, user, duration, reason)
  File "C:\Users\iiCarelessness\Desktop\All My Shit\Programs\Red-DiscordBot\cogs\punish.py", line 333, in _punish_cmd_common
    'until': timestamp,
UnboundLocalError: local variable 'timestamp' referenced before assignment`

**Comment by calebj** [comment]
Can you try [this version](https://gist.github.com/calebj/f7009d3bd3921582fc7afb79c8dd3cc0)?

**Comment by calebj** [comment]
Closed due to inactivity.
