### ISSUE TITLE
captcha cog issue

### ISSUE THREAD

**Issue by NoNotNick** [calebj/calebj-cogs#64]
So i am using captcha cog but i couldn't change the role-mode because of this issue 

`Traceback (most recent call last):
  File "lib\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\rexal\Desktop\stuff\scripts\gits\Red-DiscordBot\cogs\captcha.py", line 954, in captchaset_role_mode
    if role_mode.lower().startswith('unverified'):
AttributeError: 'NoneType' object has no attribute 'lower'`

**Comment by calebj** [comment]
Fixed in 0666b2888e60d4feb7c17e477ecedad76eac7283
